apiVersion: v1
kind: Service
metadata:
  name: tpl
  namespace: biodiversity
  labels:
    app: tpl
spec:
  type: ClusterIP
  selector:
    app: tpl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
